### ISSUE TITLE
An error occurred while running the same code on win10

### ISSUE THREAD

**Issue by york-yang-me** [kendricktan/hello-world-zk-dapp#1]
win10 node version:10.12.0 
`circuit.circom:13,2-16,3   Sizes in assignment must be the same
(node:7420) UnhandledPromiseRejectionWarning: TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at compiler.then (C:\Users\Lenovo\AppData\Roaming\npm\node_modules\circom\cli.js:160:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
(node:7420) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch blo
ck, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
`
I hope to someone can help me to solve this problem. Thank you.

**Comment by Annabelle-Li** [comment]
ubuntu18.04 node -v12.14.1
There is an error when i tried to compile the circuit. The detail is as follows:

ERROR at /home/lala/APP/circuits/circuit.circom:16,2-19,3   Sizes in assignment must be the same
{
 "type": "OP",
 "op": "=",
 "values": [
  {
   "type": "DECLARE",
   "declareType": "VARIABLE",
   "name": {
    "type": "VARIABLE",
    "name": "BASE8",
    "selectors": [],
    "first_line": 16,
    "first_column": 6,
    "last_line": 16,
    "last_column": 11
   },
   "first_line": 16,
   "first_column": 2,
   "last_line": 16,
   "last_column": 11,
   "refId": 3
  },
  {
   "type": "ARRAY",
   "values": [
    {
     "type": "NUMBER",
     "value": "5299619240641551281634865583518297030282874472190772894086521144482721001553",
     "first_line": 17,
     "first_column": 4,
     "last_line": 17,
     "last_column": 80
    },
    {
     "type": "NUMBER",
     "value": "16950150798460657717958625567821834550301663161624707787222815936182638968203",
     "first_line": 18,
     "first_column": 4,
     "last_line": 18,
     "last_column": 81
    }
   ],
   "first_line": 16,
   "first_column": 14,
   "last_line": 19,
   "last_column": 3
  }
 ],
 "first_line": 16,
 "first_column": 2,
 "last_line": 19,
 "last_column": 3
}
Can someone help me solve this problem.Thank you.

**Comment by JustynaBroniszewska** [comment]
Hi, I had the same problem and I found [this](https://www.bountysource.com/issues/91303123-compile-error-when-using-mimc-hash). I changed the version to 0.0.34 and it worked. 😄
